name: Esegui Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installa Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Esegui test
        run: |
          echo "Eseguo i test..."
          npm install
          npm test
